### PR TITLE
Remove buggy iOS 7 specific title placement

### PR DESCRIPTION
**Pull request by stephenwoodford**
I'm not sure of Titanium's handling of positions in iOS 7 has changed but the title displayed properly without the additional top space.

### CODE REVIEW

**Comment by mcongrove** [comment]
This doesn't work for me:

http://screencast.com/t/BQBjGeltMVtE

**Comment by mcongrove** [comment]
Nevermind; this is fixed _in conjunction with_ your title wrapper.

**Comment by stephenwoodford** [comment]
Sorry about that, I had done all of these changes on one branch and then tried to split them up so you could pick and choose which changes you liked.

**Comment by mcongrove** [comment]
No worries; I actually prefer the way you did it. I just pulled them slightly out of order and confused myself :)

**Pull request merged**
